### ISSUE TITLE
PatternSyntaxException when compiling PROPERTY regexp

### ISSUE THREAD

**Issue by samlu** [ridencww/expression-evaluator#15]
I got the following exception when calling new Parser().eval("4/67")

Caused by: java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 9
    \$\{(.*)}
             ^
        at java.util.regex.Pattern.compileImpl(Native Method)
        at java.util.regex.Pattern.compile(Pattern.java:1344)
        at java.util.regex.Pattern.<init>(Pattern.java:1328)
        at com.creativewidgetworks.expressionparser.TokenType.<init>(TokenType.java:48)
        at com.creativewidgetworks.expressionparser.TokenType.<clinit>(TokenType.java:15)
        at java.util.regex.Pattern.compile(Pattern.java:950)

It works after I change PROPERTY regexp as
PROPERTY("\\$\\{(.*)\\}", true), // ${id}

Env: Android 9.x, Java 1.7

**Comment by ridencww** [comment]
Changed pushed to develop branch pending final review.

**Comment by appfrilans** [comment]
I get similar errors. Is still issue fixed?

**Comment by ridencww** [comment]
Issue corrected in release 2.3.0 and has been published to the Maven Central Repository (allow several hours to propagate).
