### ISSUE TITLE
strange behavior when setCaseSensitive(true)

### ISSUE THREAD

**Issue by samlu** [ridencww/expression-evaluator#18]
Parser parser = new Parser();

parser.setCaseSensitive(true);

parser.addVariable("c1", new Value().setValue(true));
parser.addVariable("c2", new Value().setValue(true));

parser.eval("c1 and c2");
==> crash 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.creativewidgetworks.expressionparser.Operator.equals(java.lang.Object)' on a null object reference
        at com.creativewidgetworks.expressionparser.Parser.RPNtoValue(Parser.java:985)
        at com.creativewidgetworks.expressionparser.Parser.eval(Parser.java:482)

parser.eval("c1 AND c2");
==> will recognize "AND" as an identifier

**Comment by ridencww** [comment]
In progress: InfixToRPN is not handling AND/and correctly.

**Comment by ridencww** [comment]
Issue corrected in release 2.3.0 and has been published to the Maven Central Repository (allow several hours to propagate).
